### ISSUE TITLE
Improve e2e test coverage for stringified scripts

### ISSUE THREAD

**Issue by OrKoN** [puppeteer/replay#275] opened 2022-08-23 07:19 UTC
Combined with https://github.com/puppeteer/replay/issues/268 and https://github.com/puppeteer/replay/blob/main/test/lighthouse/lighthouse-e2e.test.ts#L131 we should create e2e tests that test the stringified output to make sure the scripts are actually executable. cc @jecfish @jrandolf

**Comment by nickmccurdy** [comment] 2022-08-23 07:25
I think that's a good idea. I want to do something similar for [Testing Library Recorder Extension](https://github.com/testing-library/testing-library-recorder-extension). I've also thought about running Prettier and TypeScript on the emitted output and using snapshot to automate managing changes in output.

**Comment by 0373501775** [comment] 2022-10-08 15:56
#318 #
Duplicate of #

**Comment by 0373501775** [comment] 2022-10-08 15:57
#329

**Comment by Vicotpf** [comment] 2022-10-20 18:27
> Combined with #268 and https://github.com/puppeteer/replay/blob/main/test/lighthouse/lighthouse-e2e.test.ts#L131 we should create e2e tests that test the stringified output to make sure the scripts are actually executable. cc @jecfish @jrandolf

**Comment by OrKoN** [comment] 2022-10-27 13:40
I have added a so-called "everything" test that tries to test every possible replay feature on a single site: https://github.com/puppeteer/replay/blob/main/test/everything.test.ts The site produces the log based on the actions and it's expected that any kind of runner results in the exactly same log. Still we need to add coverage for iframes and targets and re-package the test so that it can be easily integrated into other projects.

**Closed** 2023-01-24 10:55 UTC
Labels: enhancement
